"""fix_user_settings_timestamps_defaults

Revision ID: 5be5fe5ccc68
Revises: 65eacab2f822
Create Date: 2025-07-28 22:16:13.231243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be5fe5ccc68'
down_revision: Union[str, Sequence[str], None] = '65eacab2f822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing server defaults for user_settings timestamps
    op.alter_column('user_settings', 'created_at',
                    server_default=sa.text('now()'))
    op.alter_column('user_settings', 'updated_at',
                    server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
