"""remove_demo_timezone_field

Revision ID: 9e55ed922174
Revises: 4e3a704959c8
Create Date: 2025-07-28 00:43:18.175501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e55ed922174'
down_revision: Union[str, Sequence[str], None] = '4e3a704959c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
