"""Remove auth_provider and external_id columns

Revision ID: cfcc2b66a9df
Revises: 379d3cca8ac4
Create Date: 2025-07-24 15:19:01.119855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcc2b66a9df'
down_revision: Union[str, Sequence[str], None] = '379d3cca8ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_auth_provider_external_id_key'), 'users', type_='unique')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_auth_provider_external_id_key'), 'users', ['auth_provider', 'external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
